replicaCount: 1

image:
  repository: devidevops447/wordpress-beta
  tag: v287.1
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  host: stage.wordpress.showmysite.click
  certificateArn: arn:aws:acm:ap-south-1:741616023974:certificate/a118ec68-3e2e-4be5-b61a-f3e66dcafda0
