apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /var/www/html/wp-content/uploads || true"]
        volumeMounts:
        - name: wordpress-pvc
          mountPath: /var/www/html/wp-content/uploads

      containers:
      - name: wordpress
        image: devidevops447/wordpress-beta:v2.70
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-pvc
          mountPath: /var/www/html/wp-content/uploads
        - name: wp-config-volume
          mountPath: /var/www/html/wp-config.php
          subPath: wp-config.php
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: WORDPRESS_DB_HOST
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: WORDPRESS_DB_NAME
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: WORDPRESS_DB_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: WORDPRESS_DB_PASSWORD

      volumes:
      - name: wp-config-volume
        configMap:
          name: wp-config

      - name: wordpress-pvc
        persistentVolumeClaim:
          claimName: wordpress-pvc

      - name: upload-volume
        configMap:
          name: upload
