apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
- ingress.yaml
- configmap.yaml
namePrefix: stg-
namespace: nexus
images:
- name: registry.gitlab.farenexushub.com/nexus/drupal/drupal
  newTag: f0047238
