apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wordpress-stage
namePrefix: stage-

resources:
- ../../base
- ingress.yaml

images:
- name: devidevops447/wordpress-beta
  newTag: STAGE_IMAGE_TAG
