apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workshop
namePrefix: stage-

resources:
- ../../base
- ingress.yaml

images:
- name: devidevops447/wordpress-beta
  newTag: v4444444
