apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: stage-
namespace: workshop

resources:
- ../../base
- ingress.yaml


images:
- name: devidevops447/cloud-native-app-frontend-beta
  newTag: v77
