apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workshop
namePrefix: stage-

resources:
- ../../base
- ingress.yaml
- namespace.yaml

images:
- name: devidevops447/cloud-native-app-backend-beta
  newTag: v77
