apiVersion: v1
kind: Service
metadata:
  name: cloud-native-app-backend
spec:
  selector:
    app: cloud-native-app-backend
  ports:
  - port: 80            # ✅ Ingress talks on 8080
    targetPort: 8080    # ✅ Forward to Next.js
