apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-native-app-frontend
  labels:
    app: cloud-native-app-frontend
spec:
  replicas: 1

  selector:
    matchLabels:
      app: cloud-native-app-frontend

  template:
    metadata:
      labels:
        app: cloud-native-app-frontend
    spec:
      containers:
      - name: cloud-native-app-frontend
        image: devidevops447/cloud-native-app-frontend-beta:latest
        ports:
        - containerPort: 3000   # âœ… FIX

        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
