apiVersion: v1
kind: Service
metadata:
  name: cloud-native-app-frontend
spec:
  selector:
    app: cloud-native-app-frontend
  ports:
  - port: 3000            # ✅ Ingress talks on 3000
    targetPort: 3000    # ✅ Forward to Next.js
