apiVersion: v1
kind: Service
metadata:
  name: cloud-native-app-frontend
spec:
  selector:
    app: cloud-native-app-frontend
  ports:
  - port: 80          # ğŸ‘ˆ Ingress talks here
    targetPort: 3000  # ğŸ‘ˆ App runs here

  